apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
      - name: ENVIRONMENT
        value:"development"
    ports:
    - containerPort: 80
